### PR TITLE
Added interface labels on drawio Ring topo

### PR DESCRIPTION
**Pull request by viniarck**
Added interface labels on drawio Ring topo, to facilitate correlating expected information where flows should be installed

### CODE REVIEW

**Comment by italovalcy** [comment]
> LGTM

Just a minor suggestion: can you please update the PNG file on the repo with the labels?

**Comment by viniarck** [comment]
> > LGTM
> 
> Just a minor suggestion: can you please update the PNG file on the repo with the labels?

Good catch @italovalcy, I've just exported it too. I've noticed that some paths that you've drawn before are no longer there, we might need to update the source if you still need these primary/backup path drawings, let me know.

**Comment by italovalcy** [comment]
> > > LGTM
> > 
> > 
> > Just a minor suggestion: can you please update the PNG file on the repo with the labels?
> 
> Good catch @italovalcy, I've just exported it too [ff98b0b](https://github.com/amlight/kytos-end-to-end-tests/commit/ff98b0b99b11ffa174db767fa13133b221926e93). I've noticed that some paths that you've drawn before are no longer there, we might need to update the source if you still need these primary/backup path drawings, let me know.

Excellent, @viniarck ! Please go ahead with the merge! the paths I've drawn before are not necessary (in fact, they shouldn't be there anyway!) thank you!

**Comment by viniarck** [comment]
> > > > LGTM
> > > 
> > > 
> > > Just a minor suggestion: can you please update the PNG file on the repo with the labels?
> > 
> > 
> > Good catch @italovalcy, I've just exported it too [ff98b0b](https://github.com/amlight/kytos-end-to-end-tests/commit/ff98b0b99b11ffa174db767fa13133b221926e93). I've noticed that some paths that you've drawn before are no longer there, we might need to update the source if you still need these primary/backup path drawings, let me know.
> 
> Excellent, @viniarck ! Please go ahead with the merge! the paths I've drawn before are not necessary (in fact, they shouldn't be there anyway!) thank you!

Sounds good. Appreciated your review, let's ship it then.

**Pull request merged**
