### PR TITLE
Updated `test_010_create_mw_on_switch_should_move_evc` to avoid false positive during convergence

### LINKED ISSUE #145: Maintenance test_010_create_mw_on_switch_should_move_evc has been flaky
This maintenance [`test_010_create_mw_on_switch_should_move_evc`](https://github.com/amlight/kytos-end-to-end-tests/blob/master/tests/test_e2e_15_maintenance.py#L86) test case has been a bit flaky recently:

```
=================================== FAILURES ===================================
_______ TestE2EMaintenance.test_010_create_mw_on_switch_should_move_evc ________
self = <tests.test_e2e_15_maintenance.TestE2EMaintenance object at 0x7fbe205eac70>
    def test_010_create_mw_on_switch_should_move_evc(self):
        """Tests the EVC behaviors during maintenance
        Test:
            /api/kytos/maintenance on POST
        """
    
        self.restart_and_create_circuit()
    
        # Sets up the maintenance window information
        mw_start_delay = 60
        mw_duration = 60
        start = datetime.now() + timedelta(seconds=mw_start_delay)
        end = start + timedelta(seconds=mw_duration)
    
        # Sets up the maintenance window data
        payload = {
            "description": "mw for test 010",
            "start": start.strftime(TIME_FMT),
            "end": end.strftime(TIME_FMT),
            "items": [
                "00:00:00:00:00:00:00:02"
            ]
        }
    
        # Creates a new maintenance window
        api_url = KYTOS_API + '/maintenance'
        response = requests.post(api_url, data=json.dumps(payload), headers={'Content-type': 'application/json'})
        assert response.status_code == 201, response.text
        data = response.json()
        assert 'mw_id' in data
    
        # Waits for the MW to start
        time.sleep(mw_start_delay + 10)
    
        # Switch 1 and 3 should have 3 flows; Switch 2 should have only 1 flow.
        s1, s2, s3 = self.net.net.get('s1', 's2', 's3')
        flows_s1 = s1.dpctl('dump-flows')
        flows_s2 = s2.dpctl('dump-flows')
        flows_s3 = s3.dpctl('dump-flows')
        assert len(flows_s1.split('\r\n ')) == BASIC_FLOWS + 2
>       assert len(flows_s3.split('\r\n ')) == BASIC_FLOWS + 2
E       AssertionError: assert 6 == (3 + 2)
E        +  where 6 = len([' cookie=0x0, duration=90.459s, table=0, n_packets=0, n_bytes=0, priority=50000,dl_src=ee:ee:ee:ee:ee:01 actions=CONT...=92.360s, table=0, n_packets=56, n_bytes=2352, priority=1000,dl_vlan=3799,dl_type=0x88cc actions=CONTROLLER:65535\r\n'])
E        +    where [' cookie=0x0, duration=90.459s, table=0, n_packets=0, n_bytes=0, priority=50000,dl_src=ee:ee:ee:ee:ee:01 actions=CONT...=92.360s, table=0, n_packets=56, n_bytes=2352, priority=1000,dl_vlan=3799,dl_type=0x88cc actions=CONTROLLER:65535\r\n'] = <built-in method split of str object at 0x1d777a0>('\r\n ')
E        +      where <built-in method split of str object at 0x1d777a0> = ' cookie=0x0, duration=90.459s, table=0, n_packets=0, n_bytes=0, priority=50000,dl_src=ee:ee:ee:ee:ee:01 actions=CONTR...n=92.360s, table=0, n_packets=56, n_bytes=2352, priority=1000,dl_vlan=3799,dl_type=0x88cc actions=CONTROLLER:65535\r\n'.split
```

However, a single execution sometimes doesn't fail (I don't have much statistics about it atm, since e2e on my computer is timeouting again, I'm trying to fix that). 

```
+ python3 -m pytest tests/ -k test_010_create_mw_on_switch_should_move_evc
============================= test session starts ==============================
platform linux -- Python 3.9.2, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
rootdir: /builds/amlight/kytos-end-to-end-tester/kytos-end-to-end-tests
plugins: timeout-2.0.2
collected 199 items / 198 deselected / 1 selected
tests/test_e2e_15_maintenance.py .                                       [100%]
```

### PR DESCRIPTION
**Pull request by viniarck**
Fixes #145 

Updated `test_010_create_mw_on_switch_should_move_evc` to avoid false positive during convergence. 

Here's the rationale:

- Since we currently have a very low and aggressive `CONSISTENCY_MIN_VERDICT_INTERVAL = 3`, `flow_manager` consistency check could prematurely kicks in. So, instead of checking flows mid-convergence, I've replaced it to check the output of the EVC of the `current_path` on `GET /v2/evc/<evc_id>`, confirming that it switched and also a ping between hosts.
- I've maintained `dump-flows` asserts, however only at the beginning and at the end of the test where we have a relatively large interval where it shouldn't be converging anymore. If we hit more issues when checking the flows, then it's because it never converged (or NApps aren't deleting/installing flows correctly) so we might have a bug.

I've run  this updated test case ten times locally no failures so far:

```
+ for i in {1..10}
+ echo 'iteration 10'
+ python3 -m pytest -s -vv --timeout=300 tests/ -k test_010_create_mw_on_switch_should_move_evc
iteration 10
============================= test session starts ==============================
platform linux -- Python 3.9.2, pytest-6.2.5, py-1.11.0, pluggy-1.0.0 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /tests
plugins: timeout-2.0.2
timeout: 300.0s
timeout method: signal
timeout func_only: False
collecting ... collected 199 items / 198 deselected / 1 selected

*** Error setting resource limits. Mininet's performance may be affected.
tests/test_e2e_15_maintenance.py::TestE2EMaintenance::test_010_create_mw_on_switch_should_move_evc PASSED
========== 1 passed, 198 deselected, 34 warnings in 133.90s (0:02:13) ==========
```

### CODE REVIEW

**Comment by viniarck** [comment]
@italovalcy thanks for pointing out the logs on ultralog they were very valuable

**Comment by viniarck** [comment]
Regarding `CONSISTENCY_MIN_VERDICT_INTERVAL = 3`, as a general rule, this interval should accommodate the slowest expected convergence, and should work relatively slow, so this is something that I think we should review on our tests to rely less aggressively on this interval. This interval is already the last knob available to control when consistency check kicks in, if you have a case where you're network doesn't convergence within this interval, you'll have instability until it eventually converges, assuming the network switches doesn't get overwhelmed. If we need to clean up on flows, I think we should rely on other methods like explicitly deleting flows when needed, since initially flows should be loaded during restart or initial handshake. I'll map this in a new issue to continue the discussion and maybe we can add include it in the enhancements we'll make, but just opening this thread initially here. Let me know what you think.

**Review by italovalcy — APPROVED** [review]
LGTM! Excellent refactoring of the test! Also, good to see you decreased the sleep interval preserving the logic behind it.

**Comment by viniarck** [comment]
> LGTM! Excellent refactoring of the test! Also, good to see you decreased the sleep interval preserving the logic behind it.

Thanks, @italovalcy . Btw, I've mapped this enhancement https://github.com/amlight/kytos-end-to-end-tests/issues/172 to adapt `CONSISTENCY_MIN_VERDICT_INTERVAL` and find a balance there.

**Pull request merged**
