### PR TITLE
Modified tests to test priority default values

### PR DESCRIPTION
**Pull request by Alopalao**
Tests for changes from `mef_eline` PR [#214](https://github.com/kytos-ng/mef_eline/pull/214)

### CODE REVIEW

**Comment by Alopalao** [comment]
Test results
```
tests/test_e2e_01_kytos_startup.py ..                                    [  2%]
tests/test_e2e_10_mef_eline.py .........Xss.....x....x.....              [ 33%]
tests/test_e2e_11_mef_eline.py .....                                     [ 39%]
tests/test_e2e_12_mef_eline.py .....xx.                                  [ 48%]
tests/test_e2e_13_mef_eline.py .....xxXx......xxXx.XXxX.xxxx..x......... [ 94%]
...                                                                      [ 97%]
tests/test_e2e_14_mef_eline.py x                                         [ 98%]
tests/test_e2e_15_mef_eline.py .                                         [100%]
```

**Review by viniarck — APPROVED** [review]
LGTM. Thanks for covering this and also running the e2e tests.

**Review by italovalcy — APPROVED** [review]
LGTM

**Comment by viniarck** [comment]
Let's ship this.

**Pull request merged**
